app = 'botzin'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
  TIMEZONE_OFFSET = "-3"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "300s"  # 5 minutos para inicialização
    method = "GET"
    path = "/"

[mounts]
  source = "whatsapp_data"
  destination = "/data"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1